package me.lokka30.levelledmobs.rules;

public enum VanillaBonusEnum {
    ATTACKING_SPEED_BOOST,
    BABY_SPEED_BOOST,
    COVERED_ARMOR_BONUS,
    DRINKING_SPEED_PENALTY,
    FLEEING_SPEED_BOOST,
    LEADER_ZOMBIE_BONUS,
    RANDOM_SPAWN_BONUS,
    RANDOM_ZOMBIE_SPAWN_BONUS,
    SPRINTING_SPEED_BOOST,
    ZOMBIE_REINFORCE_CALLEE,
    ZOMBIE_REINFORCE_CALLER
}
