/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "LevelledMobs-Parent"

include(":levelledmobs-plugin")
include(":levelledmobs-api")

plugins{
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}