# LevelledMobs | The Ultimate RPG Mob Levelling Plugin

# TODO

# What debugging systems are enabled in the plugin?
# This list is empty by default.
debug: []

# What integrations are force-disabled in the plugin?
# This list is empty by default.
disabled-integrations: []

# Don't touch any of this unless you know what you're doing,
# or, unless a LevelledMobs maintainer suggested you do so.
file:
  version: '??' #TODO
  generated-with: '${project.version}'