name: LevelledMobs
version: ${project.version}
main: io.github.lokka30.levelledmobs.LevelledMobs
softdepend: [WorldGuard]
api-version: '1.15'
load: STARTUP
author: lokka30
description: ${project.description}
website: 'https://github.com/lokka30/LevelledMobs/wiki'

commands:
  levelledmobs:
    description: Manage LevelledMobs
    aliases: [leveledmobs]
    usage: /<command> [killall/info]

permissions:
  levelledmobs.*:
    description: all levelledmobs permissions
    default: op
    children:
      levelledmobs.killall: true
  levelledmobs.killall:
    description: access to /levelledMobs killAll [world]
    default: op