name: LevelledMobs
version: ${project.version}
main: io.github.lokka30.levelledmobs.LevelledMobs
softdepend: [WorldGuard]
api-version: '1.13'
load: STARTUP
author: lokka30
description: ${project.description}
website: 'https://github.com/lokka30/LevelledMobs/wiki'

commands:
  levelledmobs:
    description: Manage LevelledMobs
    aliases: [leveledmobs, lm, lvlmobs]
    usage: /<command> [killall/reload/summon/info]

permissions:
  levelledmobs.*:
    description: 'Access to all LevelledMobs permissions.'
    default: op
    children:
      levelledmobs.command.*: true
      levelledmobs.killall: true
      levelledmobs.summon: true
      levelledmobs.kill.*: true

  levelledmobs.command.*:
    description: 'Access to all LevelledMobs commands.'
    default: op
    children:
      levelledmobs.command: true
      levelledmobs.command.kill.*: true
      levelledmobs.command.reload: true
      levelledmobs.command.info: true

  levelledmobs.command:
    description: 'Access to `/levelledmobs`.'
    default: true

  levelledmobs.command.kill.*:
    description: 'Access to `/levelledmobs kill all` and `/levelledmobs kill near`.'

  levelledmobs.command.kill:
    description: 'Access to `/levelledmobs kill`.'
    default: op

  levelledmobs.command.kill.all:
    description: 'Access to `/levelledmobs kill all`.'
    default: op

  levelledmobs.command.kill.near:
    description: 'Access to `/levelledmobs kill near`.'
    default: op

  levelledmobs.command.reload:
    description: 'Access to `/levelledmobs reload`.'
    default: op

  levelledmobs.command.info:
    description: 'Access to `/levelledmobs info`.'
    default: true

  #TODO CONVERT
  levelledmobs.kill.*:
    description: 'Access to `/levelledmobs kill`.'
    default: op
  levelledmobs.kill.near:
    description: 'access to ''/levelledMobs kill near'''
    default: op
  levelledmobs.kill.all:
    description: 'access to ''/levelledmobs kill all'''
    default: op
  levelledmobs.summon:
    description: 'access to ''/levelledmobs summon'''
    default: op