name: LevelledMobs
version: ${project.version}
main: io.github.lokka30.levelledmobs.LevelledMobs
softdepend: [ WorldEdit, WorldGuard, ProtocolLib ]
api-version: '1.13'
load: STARTUP
author: lokka30
description: ${project.description}
website: 'https://github.com/lokka30/LevelledMobs/wiki'

commands:
  levelledmobs:
    description: Manage LevelledMobs
    aliases: [ leveledmobs, lm, lvlmobs ]
    usage: /<command> [killall/reload/summon/info]

permissions:
  levelledmobs.*:
    description: 'Access to all LevelledMobs permissions.'
    default: op
    children:
      levelledmobs.compatibility-notice: true
      levelledmobs.command.*: true

  levelledmobs.command.*:
    description: 'Access to all LevelledMobs commands.'
    default: op
    children:
      levelledmobs.command: true
      levelledmobs.command.summon: true
      levelledmobs.command.kill.*: true
      levelledmobs.command.reload: true
      levelledmobs.command.info: true
      levelledmobs.command.compatibility: true

  levelledmobs.compatibility-notice:
    description: 'Ability to view the compatibility notice on join if any possible incompatibilities are found on startup.'
    default: op

  levelledmobs.command:
    description: 'Access to `/levelledmobs`.'
    default: true

  levelledmobs.command.summon:
    description: 'access to ''/levelledmobs summon'''
    default: op

  levelledmobs.command.kill.*:
    description: 'Access to `/levelledmobs kill all` and `/levelledmobs kill near`.'
    default: op
    children:
      levelledmobs.command.kill.all: true
      levelledmobs.command.kill.near: true

  levelledmobs.command.kill:
    description: 'Access to `/levelledmobs kill`.'
    default: op

  levelledmobs.command.kill.all:
    description: 'Access to `/levelledmobs kill all`.'
    default: op

  levelledmobs.command.kill.near:
    description: 'Access to `/levelledmobs kill near`.'
    default: op

  levelledmobs.command.reload:
    description: 'Access to `/levelledmobs reload`.'
    default: op

  levelledmobs.command.info:
    description: 'Access to `/levelledmobs info`.'
    default: true

  levelledmobs.command.compatibility:
    description: 'Access to `/levelledmobs compatibility`.'
    default: op