name: ${project.name}
version: ${project.version}
main: io.github.lokka30.levelledmobs.LevelledMobs
api-version: '1.15'
load: STARTUP

author: lokka30
description: ${project.description}
website: https://www.spigotmc.org/resources/%E2%98%85levelledmobs%E2%98%85-a-simple-drag-n-drop-solution-for-mob-attributes.74304/

commands:
  LevelledMobs:
    description: Various plugin information.