# LevelledMobs | The Ultimate RPG Mob Levelling Plugin

# (!) This is NOT a configuration file. This file is read
#     by your server software (SpigotMC/PaperMC/etc) to
#     ensure LevelledMobs operates properly and registers
#     its commands & permissions to the server. Do not change
#     anything in this file unless a LevelledMobs developer
#     recommends you do so, which would be HIGHLY unlikely.

# General plugin information
name: 'LevelledMobs'
version: '${project.version}'
authors: [ 'lokka30', 'stumper66 (aka. PenalBuffalo)', 'UltimaOath (aka. Oathkeeper)' ]
description: '${project.description}'
website: 'https://github.com/lokka30/LevelledMobs/'

# Other info for plugin loader
main: 'me.lokka30.levelledmobs.LevelledMobs'
softdepend: [ 'WorldEdit', 'WorldGuard', 'ProtocolLib', 'PlaceholderAPI', 'NBTAPI' ]
api-version: '1.13' # Yes, '1.13' is intended. Don't change it.
load: 'POSTWORLD'

# Base commands registered by the plugin
commands:
  levelledmobs:
    description: 'Run various LevelledMobs management/info commands.'
    aliases: [ 'leveledmobs', 'lm', 'lvlmobs' ]
    usage: '/<command>'

# All non-dynamic permissions registered by the plugin
permissions:

  #TODO

  levelledmobs.*:
    default: op
    #TODO