package io.github.arcaneplugins.levelledmobs.rules

/**
 * Each available multiplier that can be used in rules.yml
 *
 * @author stumper66
 * @since 3.7.5
 */
enum class VanillaBonusEnum {
    ARMOR_MODIFIER,  // NOT NEEDED, BASED ON ITEM IN ARMOR SLOTS
    ARMOR_TOUGHNESS,  // NOT NEEDED, BASED ON ITEM IN ARMOR SLOTS
    ATTACKING_SPEED_BOOST,
    BABY_SPEED_BOOST,
    COVERED_ARMOR_BONUS,
    DRINKING_SPEED_PENALTY,
    FLEEING_SPEED_BOOST,
    HORSE_ARMOR_BONUS,  // NOT NEEDED, BASED ON ITEM IN ARMOR SLOTS
    KNOCKBACK_RESISTANCE,  // NOT NEEDED, BASED ON ITEM/ATTRIBUTE
    LEADER_ZOMBIE_BONUS,
    RANDOM_SPAWN_BONUS,
    RANDOM_ZOMBIE_SPAWN_BONUS,
    SPRINTING_SPEED_BOOST,
    TOOL_MODIFIER,  // NOT NEEDED, BASED ON ITEM IN HAND
    WEAPON_MODIFIER,  // NOT NEEDED, BASED ON ITEM IN HAND
    ZOMBIE_REINFORCE_CALLEE,
    ZOMBIE_REINFORCE_CALLER
}