#   -------------------------------------------------------------------------------------
#   ----------------------------------------  -  ----------------------------------------
#    _                   _ _          _       |
#   | |    _____   _____| | | ___  __| |      |   Developer: PenalBuffalo
#   | |   / _ \ \ / / _ \ | |/ _ \/ _` |      |   ko-fi.com/penalbuffalo
#   | |__|  __/\ V /  __/ | |  __/ (_| |      |
#   |_____\___| \_/ \___|_|_|\___|\__,_|_     |   Original Author: Lokka30
#            |  \/  | ___ | |__  ___| || |    |   ko-fi.com/lokka30
#            | |\/| |/ _ \| '_ \/ __| || |_   |
#            | |  | | (_) | |_) \__ \__   _|  |   Support & Wiki: UltimaOath
#            |_|  |_|\___/|_.__/|___/  |_|    |   ko-fi.com/ultimaoath
#
#   ----------------------   The Ultimate Mob Levelling Solution   ----------------------
#
#   Documentation                             |   Support
#   . Wiki: tinyurl.com/lm4-wiki              |   . Discord: discord.gg/RQ8M4A5
#   . FAQ: tinyurl.com/lm4-wiki-faq           |   Please review our plugin!
#   . Ex. Rules: tinyurl.com/lm4-ex-rules     |   . Hangar - tinyurl.com/lm-hangar
#   . Ex. Drops: tinyurl.com/lm4-ex-drops     |   . SpigotMC - tinyurl.com/lm-spigotmc
#                                             |
#   ----------------------------------------  -  ----------------------------------------
#   -------------------------------------------------------------------------------------
#
#   ---------------  -  ------------------------------
#        Section 01  |  Settings
#   ---------------  -  ------------------------------

# ||  ADVANCED USERS ONLY | DEBUG
# ||  Do not touch this unless a LM developer tells you to.
# ||  These settings print a lot of 'behind the scenes'
# ||  information about LevelledMobs' operations to the console.
# ||  With LevelledMobs4, we suggest using the command: /lm debug
debug-misc: [ ]

# ||  This is a good update checker - it doesn't freeze
# ||  your server startup since it is asynchronous, it
# ||  only speaks if it found an update, and it only runs
# ||  once every server startup. Pointless to disable.
use-update-checker: true

# ||  ADVANCED USERS ONLY
# ||  If your server software (e.g. Paper) has
# ||  the Adventure library in it, then LevelledMobs
# ||  will use it, so long this setting is enabled.
# ||  CraftBukkit and Spigot servers do not have
# ||  this library, although PaperMC servers and
# ||  all PaperMC forks (Airplane, etc) do.
# ||  It is recommended that you keep this enabled.
use-adventure: true

# ||  ADVANCED USERS ONLY
# ||  Do not touch this unless a LM developer tells you to.
# ||  If your server software (e.g. Paper) has the Adventure
# ||  Library in it, then you can change this to false and
# ||  use MiniMessage for nametag parsing.
use-legacy-serializer: true

# ||  ADVANCED USERS ONLY
# ||  Do not touch this unless a LM developer tells you to.
# ||  This system controls the repeating asynchronous listener which
# ||  maintains the accuracy of levelling and nametag information.
# ||  This is very important and resource sensitive, so it is not
# ||  suggested to alter these settings without testing beforehand.
# ||  This system acts as a garbage collection and verification
# ||  mechanism, as well as a form of 'rechecking' entities to ensure
# ||  they follow the rules of the system.
async-task-update-period: 3
async-task-max-blocks-from-player: 320

# ||  ADVANCED USERS ONLY
# ||  Do not touch this unless a LM developer tells you to.
# ||  Enables the on-spawn listener to apply levels to entities.
# ||  Will be enabled until number of online players exceed this value.
level-mobs-upon-spawn-max-players: 10

# ||  ADVANCED USERS ONLY
# ||  Do not touch this unless a LM developer tells you to.
# ||  When enabled mobs will received nametag update packets when they
# ||  receive damage from any source. If disabled only player caused
# ||  damage will send a nametag packet.
# ||  Will be enabled until number of online players exceed this value.
update-mobs-upon-nonplayer-damage-max-players: 5

# ||  ADVANCED USERS ONLY
# ||  Do not touch this unless a LM developer tells you to.
# ||  Enables the on-load listener to apply levels to entities once
# ||  a chunk has been loaded. If false, this listener will be disabled.
ensure-mobs-are-levelled-on-chunk-load: true

# ||  ADVANCED USERS ONLY
# ||  Do not touch this unless a LM developer tells you to.
# ||  This controls the mob processing delay (in in-game ticks)
# ||  after a mob is marked to be levelled. Note, that there is
# ||  a 1 tick delay in addition to this setting.
mob-process-delay: 0

# ||  ADVANCED USERS ONLY
# ||  Do not touch this unless a LM developer tells you to.
# ||  Should nametag packets be ignored if the mob has died?
assert-entity-validity-with-nametag-packets: true

# ||  When player kill exceed amount of levelled mobs in
# ||  a chunk(within given period). Should we send message
# ||  to player to inform him?
exceed-kill-in-chunk-message: true

# ||  This sets a hard limit on the number of entities
# ||  you can summon using the LevelledMobs summon command.
# ||  This is to prevent accidental crashes.
customize-summon-command-limit: 10

# ||  What is the max distance the summon command will
# ||  spawn mobs away from players?
summon-command-spawn-max-distance-from-player: 5

# ||  What is the min distance the summon command will
# ||  spawn mobs away from players?
summon-command-spawn-min-distance-from-player: 3

# ||  Do not touch this unless a LM developer tells you to.
# ||  This sets a hard limit on the number of times a command
# ||  being 'dropped' from the Custom Drops system can be
# ||  performed in a loop. This is to prevent accidental crashes.
customcommand-amount-limit: 100

# ||  When set to true, nametags will show the mob name
# ||  translated to your client language settings.
# ||  However some older or hacked clients do not support
# ||  this and will show the translation key instead.
use-translation-components: true

# ||  These settings pertian to Player Levelling, which sets
# ||  the updating period for the Player Levelling tasks.
player-levelling-relevel-min-time: 5s

# ||  This setting determines how far away an entity can be
# ||  for it to register under `%levelledmobs_mob-target%`.
nametag-placeholder-maxblocks: 30

# ||  What conditions should a mob have in order for the
# ||  LevelledMobs kill command to 'skip' it (not kill the mob)?
kill-skip-conditions:
  is-nametagged: true
  is-tamed: true
  is-leashed: true
  is-transforming: true
  is-villager: true
  entitytype:
    included-groups: ['all_passive_mobs']
    included-list: ['']

# ||  Should mob heads be multiplied by LevelledMobs'
# ||  drop multiplier? A considerable amount of servers
# ||  have heads in their economies, so it is set to false
# ||  by default as to not harm their economies.
mobs-multiply-head-drops: false

# ||  When set to true, every mob is checked to make sure it has
# ||  the latest rules applied by comparing a stored hash string.
check-mob-hash: true

# ||  When using the LM Summon command should it print the results
# ||  in the console or player that executed the command
print-lm-summon-results: true

# ||  ADVANCED USERS ONLY
# ||  The amount of time that should elapse before
# ||  the LEW (LivingEntityWrapper) cache is cleared.
lew-cache-clear-period: 3m

# ||  This setting will exclude players who are in creative
# ||  mode when the Player Level Modifier is determining values.
exclude-players-in-creative: false


#
#   ---------------  -  ------------------------------
#        Section 02  |  Developer Settings / Do Not Edit Beyond This Point
#   ---------------  -  ------------------------------
#
file-version: 37
