api-version: '1.18'
authors: ['lokka30', 'PenalBuffalo', 'UltimaOath']
description: 'The Ultimate RPG Mob Levelling Solution'
main: 'io.github.arcaneplugins.levelledmobs.bukkit.LevelledMobs'
name: 'LevelledMobs'
version: '${project.version}'
website: 'https://github.com/lokka30/LevelledMobs/'

softdepend:
  - 'Essentials'      # EssentialsX is soft-dep as it is used for the 'home distance' placeholder.
  - 'NBTAPI'          # NBTAPI is soft-dep as the custom drops system allows NBT control.
  - 'PlaceholderAPI'  # PlaceholderAPI is soft-dep as LM supplies placeholders for it.
  - 'ProtocolLib'     # ProtocolLib is soft-dep as it is the fallback nametag packet handler.
  - 'SimplePets'      # SimplePets is soft-dep as we must use its API for compatibility.
  - 'WorldEdit'       # WorldEdit is soft-dep for WorldGuard.
  - 'WorldGuard'      # WorldGuard is soft-dep for the Region API usage.

libraries:
  - 'org.spongepowered:configurate-yaml:4.1.2'

permissions:
  'levelledmobs.*':
    default: op
    description: 'A collection of most LevelledMobs permissions.'
    children:
      'levelledmobs.command.*': true
      'levelledmobs.receive-update-notifications': true
      'levelledmobs.debug': true

  'levelledmobs.command.*':
    default: op
    description: 'A collection of all of the permissions for LevelledMobs commands.'
    children:
      'levelledmobs.command.levelledmobs.*': true

  'levelledmobs.command.levelledmobs.*':
    default: op
    description: 'A collection of all of the permissions for the `/levelledmobs` command.'
    children:
      'levelledmobs.command.levelledmobs': true
      'levelledmobs.command.levelledmobs.about': true
      'levelledmobs.command.levelledmobs.reload': true

  'levelledmobs.command.levelledmobs':
    default: true
    description: 'Ability to run the `/levelledmobs` base command.'

  'levelledmobs.command.levelledmobs.about':
    default: true
    description: 'Read some information about this LevelledMobs version.'
    children:
      'levelledmobs.command.levelledmobs': true

  'levelledmobs.command.levelledmobs.reload':
    default: op
    description: 'Reload the plugin''s configuration.'
    children:
      'levelledmobs.command.levelledmobs': true

  'levelledmobs.receive-update-notifications':
    default: op
    description: 'Receive update checker notifications.'

  'levelledmobs.debug':
    default: op
    description: 'Ability to use in-game LevelledMobs debug tools.'
