# LevelledMobs | The Ultimate RPG Mob Levelling Plugin

# (!) This is NOT a configuration file. This file is read
#     by your server software (SpigotMC/PaperMC/etc) to
#     ensure LevelledMobs operates properly and registers
#     its commands & permissions to the server. Do not change
#     anything in this file unless a LevelledMobs developer
#     recommends you do so, which would be HIGHLY unlikely.

# General plugin information
name: 'LevelledMobs'
version: '${project.version}'
authors: [ 'lokka30', 'stumper66 (aka. PenalBuffalo)', 'UltimaOath (aka. Oathkeeper)' ] # The LevelledMobs team
description: '${project.description}'
website: 'https://github.com/lokka30/LevelledMobs/'

# Other info for plugin loader
main: 'me.lokka30.levelledmobs.plugin.bukkit.LevelledMobs'
softdepend: [ ] #TODO
api-version: '1.13'
load: 'STARTUP' # We want it to load before the worlds so all mobs are detected.

# Base commands registered by the plugin
commands:
  levelledmobs:
    description: 'Run various LevelledMobs management/info commands.'
    aliases: [ 'leveledmobs', 'lm', 'lvlmobs' ]
    usage: '/<command>'

# All static permissions registered by the plugin
permissions:

  levelledmobs.*:
    default: op
    description: 'Gain all LevelledMobs operator permissions'
    children: #TODO
      abc: true

  levelledmobs.command.*:
    default: op
    description: 'Gain access to all LevelledMobs commands'
    children: #TODO
      abc: true

  levelledmobs.command.levelledmobs.*:
    default: op
    description: 'Gain access to /levelledmobs and all of its subcommands'
    children: #TODO
      abc: true

  levelledmobs.command.levelledmobs:
    default: op
    description: 'Gain access to the base command of /levelledmobs'

  # TODO Add other permissions